project_id = "sojrvsbqkrbxoymlwtii"

[functions.bling-oauth]
verify_jwt = false

[functions.calculate-shipping]
verify_jwt = false

[functions.process-payment]
verify_jwt = false

[functions.bling-sync]
verify_jwt = false

[functions.bling-webhook]
verify_jwt = false

[functions.appmax-webhook]
verify_jwt = false

[functions.bling-sync-single-stock]
verify_jwt = false

[functions.appmax-get-app-token]
verify_jwt = false

[functions.appmax-authorize]
verify_jwt = false

[functions.appmax-generate-merchant-keys]
verify_jwt = false

[functions.appmax-healthcheck]
verify_jwt = false

[functions.cleanup-logs]
verify_jwt = false

[functions.repair-images]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.robots]
verify_jwt = false

[functions.appmax-healthcheck-ping]
verify_jwt = false

[functions.checkout-create-session]
verify_jwt = false

[functions.integrations-test]
verify_jwt = false

[functions.yampi-webhook]
verify_jwt = false

[functions.yampi-sync-sku]
verify_jwt = false
